# Generated by Django 5.2 on 2025-05-14 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, upload_to='Imagens/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Programação',
                'verbose_name_plural': 'Programações',
            },
        ),
    ]
