# Generated by Django 5.2 on 2025-05-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=150)),
                ('imagem', models.CharField(max_length=100)),
            ],
        ),
    ]
