# Generated by Django 5.2 on 2025-05-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacao',
            options={'verbose_name': 'Programação', 'verbose_name_plural': 'Programações'},
        ),
    ]
