# Generated by Django 5.2 on 2025-05-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_programacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacao',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
