# Generated by Django 5.2 on 2025-05-13 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_programacao_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
