# Generated by Django 5.2 on 2025-05-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_programacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacao',
            name='imagem',
            field=models.ImageField(upload_to='Imagens/%Y%m%d/'),
        ),
    ]
